/**
 * This file was autogenerated from Letter_Gothic_Std_14_Bold.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _Letter_Gothic_Std_14_Bold_h_
#define _Letter_Gothic_Std_14_Bold_h_
//---------------------------------------------------------------------------------
extern const unsigned char Letter_Gothic_Std_14_Bold[];
extern const int Letter_Gothic_Std_14_Bold_size;
//---------------------------------------------------------------------------------
#endif //_Letter_Gothic_Std_14_Bold_h_
//---------------------------------------------------------------------------------
