language: c
dist: trusty
sudo: required

os:
  - linux

env:
  global:
    - DEVKITPRO=$HOME/devkitPro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC

addons:
  apt:
    packages:
      - doxygen

cache:
  directories:
    - ${DEVKITPRO}

before_install:
  - wget https://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitPPCupdate.pl

install:
  - sudo perl devkitPPCupdate.pl

script:
  - (cd GRRLIB && sudo -E make clean all install)
  - (cd examples && make)
  - (cd GRRLIB && sudo -E make PLATFORM=cube clean all)
  - doxygen grrlib.doxygen

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/doc
  github_token: $GITHUB_TOKEN
  on:
    branch: master
