/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _GRRLIBbutton_h_
#define _GRRLIBbutton_h_
//---------------------------------------------------------------------------------
extern const unsigned char GRRLIBbutton[];
extern const int GRRLIBbutton_size;
//---------------------------------------------------------------------------------
#endif //_GRRLIBbutton_h_
//---------------------------------------------------------------------------------
