/**
 * This file was autogenerated from Rockwell_Condensed_12_Bold.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _Rockwell_Condensed_12_Bold_h_
#define _Rockwell_Condensed_12_Bold_h_
//---------------------------------------------------------------------------------
extern const unsigned char Rockwell_Condensed_12_Bold[];
extern const int Rockwell_Condensed_12_Bold_size;
//---------------------------------------------------------------------------------
#endif //_Rockwell_Condensed_12_Bold_h_
//---------------------------------------------------------------------------------
