/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _GRRLIBfont_h_
#define _GRRLIBfont_h_
//---------------------------------------------------------------------------------
extern const unsigned char GRRLIBfont[];
extern const int GRRLIBfont_size;
//---------------------------------------------------------------------------------
#endif //_GRRLIBfont_h_
//---------------------------------------------------------------------------------
