/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _pixeltest_h_
#define _pixeltest_h_
//---------------------------------------------------------------------------------
extern const unsigned char pixeltest[];
extern const int pixeltest_size;
//---------------------------------------------------------------------------------
#endif //_pixeltest_h_
//---------------------------------------------------------------------------------
